rescue-mission_old/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'questions#index'
  resources :questions
end

rescue-mission_old/app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question

  validates :description,
    presence: true,
    length: { minimum: 50 }
  validates :user_id,
    presence: true
end

rescue-mission_old/app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers

  validates :title,
    uniqueness: true,
    presence: true,
    length: { minimum: 40 }
  validates :description,
    presence: true,
    length: { minimum: 150 }
  validates :user_id,
    presence: true
end

rescue-mission_old/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :questions
  has_many :answers

  validates :email,
    uniqueness: true,
    presence: true,
    format: { with: /\A([a-z0-9_\.-]+)@([\da-z\.-]+)\.([a-z\.]{2,6})\z/}

  validates :password,
    presence: true,
    uniqueness: true
end

rescue-mission_old/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def new
    @question = Question.new
  end

  def create
    @question = Question.create(question_params)
    if @question.save
      flash[:notice] = "Question added."
      redirect_to questions_path
    else
      flash[:notice] = "Invalid entry."
      redirect_to :back
    end
  end

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  protected
  def question_params
    @question_params = params.require(:question).permit(:title, :description)
    @question_params[:user_id] = session[:user_id]
  end

end

rescue-mission_old/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RescueMission</title>
  <%= stylesheet_link_tag    'normalize' %>
  <%= stylesheet_link_tag    'foundation' %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <h1><%= link_to "Home", questions_path %></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li class="active"><%= link_to "Sign In", new_user_session_path %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path %></li>
      </ul>

    </section>
  </nav>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>

</body>
</html>

rescue-mission_old/app/views/questions/index.html.erb
<h1>Questions</h1>
<% if !@questions.empty? %>
  <table>
    <tr>
      <th>Title</th>
      <th>Created at</th>
      <th></th>
    </tr>

    <% @questions.each do |question| %>
      <tr>
        <td><%= link_to question.title, question_path(question) %></td>
        <td><%= question.created_at %></td>
      </tr>
    <% end %>
  </table>

<% end %>

<br>

<% if user_signed_in? %>
  <%= link_to 'Post a new question', new_question_path %>
<% end %>

rescue-mission_old/app/views/questions/new.html.erb
<%= form_for(@question) do |f| %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rescue-mission_old/app/views/questions/show.html.erb
<h1><%= @question.title %></h1>

<p><%= @question.description %></p>