good-eats/config/routes.rb
Rails.application.routes.draw do
  root 'restaurants#index'

  resources :restaurants, only: [:index, :new, :show, :create]
  resources :reviews
  resources :restaurants, only: [] do
    resources :reviews, only: [:create, :new]
  end

end

good-eats/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :restaurants

  validates :name,
    uniqueness: true
end

good-eats/app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  belongs_to :category
  has_many :reviews

  validates :name,
    presence: true,
    uniqueness: true

  validates :address,
    presence: true

  validates :city,
    presence: true

  validates :state,
    presence: true

  validates :zip_code,
    presence: true,
    length: { minimum: 5 }
end

good-eats/app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant

  validates :body,
    presence: true

  validates :rating,
    presence: true,
    :inclusion => 1..5

  validates :restaurant_id,
    presence: true
end

good-eats/app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
    @reviews = Review.where(restaurant_id: params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:notice] = "Restaurant added!"
    else
      flash[:notice] = "Uhoh! Something went wrong. #{@restaurant.errors}"
    end
    redirect_to restaurant_path(@restaurant)
  end

  protected
  def restaurant_params
    params.require(:restaurant).permit(:name, :description, :address, :city, :state, :zip_code)
  end

end

good-eats/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.new(review_params)
    if @review.save
      flash[:notice] = "Review added!"
    else
      flash[:notice] = "Uhoh! Something went wrong. #{@review.errors}"
    end
    redirect_to restaurant_path(@restaurant)
  end

  protected
  def review_params
    params.require(:review).permit(:rating, :body)
  end
end

good-eats/app/helpers/application_helper.rb
module ApplicationHelper
end

good-eats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Good Eats" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <div class="row">
      <%= yield %>
    </div>

  </body>
</html>

good-eats/app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
  <% end %>
</ul>

good-eats/app/views/restaurants/new.html.erb
<h2> Create a new restaurant </h2>

<%= form_for @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />

  <%= f.label :description %>
  <%= f.text_field :description %>
  <br />

  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.label :city %>
  <%= f.text_field :city %>

  <%= f.label :state %>
  <%= f.text_field :state %>

  <%= f.label :zip_code %>
  <%= f.text_field :zip_code %>

  <%= f.submit %>
<% end %>

good-eats/app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<% if @restaurant.category %>
  <h3>Category: <%= @restaurant.category %></h3>
<% end %>

<p><%= @restaurant.description %></p>

<table>
  <tr>
    <td class="details">Address:</td>
    <td><%= @restaurant.address %></td>
  </tr>
  <tr>
    <td class="details">City:</td>
    <td><%= @restaurant.city %></td>
  </tr>
  <tr>
    <td class="details">State:</td>
    <td><%= @restaurant.state %></td>
  </tr>
  <tr>
    <td class="details">Zip Code:</td>
    <td><%= @restaurant.zip_code %></td>
  </tr>
</table>

<p class="review"><%= link_to "Write a review", new_restaurant_review_path(@restaurant) %> </p>

<h3>Reviews:</h3>

<ul>
  <% @reviews.each do |review| %>
    <li class="rating">Rating: <%= review.rating %> out of 5</li>
    <li><%= review.body %></li>
    <li class="timestamp">Reviewed at: <%= review.created_at %></li>
    <br>
  <% end %>
</ul>