car-listings/config/routes.rb
Rails.application.routes.draw do
  root 'manufacturers#index'
  devise_for :users

  resources :manufacturers, only: [
    :index,
    :show,
    :new,
    :create
  ]

  resources :cars, only: [
    :index,
    :show,
    :new,
    :create
  ] do
    resources :manufacturers, only: [
      :index,
      :show
    ]
  end

end

car-listings/app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :manufacturer

  validates :model, presence: true
  validates :color, presence: true
  validates :year, presence: true, :inclusion => { :in => 1920..2025 }
  validates :mileage, presence: true
  validates :manufacturer_id, presence: true
end

car-listings/app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  has_many :cars
  
  validates :name, presence: true, uniqueness: true
  validates :country, presence: true
end

car-listings/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

car-listings/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

car-listings/app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def index
    @cars = Car.order("year DESC").page(params[:page])
  end

  def new
    @car = Car.new
    @manufacturers = Manufacturer.all
  end

  def create
    @manufacturers = Manufacturer.all
    @manufacturer = Manufacturer.find(params[:car][:manufacturer_id])
    @car = Car.new(car_params)
    if @car.save
      flash[:notice] = "Car added!"
      redirect_to cars_path
    else
      render :new
    end
  end

  private

  def car_params
    params.require(:car).permit(:model, :color, :year, :mileage, :description, :manufacturer_id)
  end

end

car-listings/app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController

  def index
    @manufacturers = Manufacturer.order("name ASC").page(params[:page])
  end

  def show
    @manufacturer = Manufacturer.find(params[:id])
  end

  def new
    @manufacturer = Manufacturer.new
  end

  def create
    @manufacturer = Manufacturer.new(manufacturer_params)
    if @manufacturer.save
      flash[:notice] = "Manufacturer added!"
      redirect_to manufacturers_path
    else
      render :new
    end
  end

  private

  def manufacturer_params
    params.require(:manufacturer).permit(:name, :country)
  end

end

car-listings/app/views/cars/index.html.erb
<h1>Cars</h1>

<%= link_to "Add a new car", new_car_path %>

<table>
  <tr>
    <th>Manufacturer</th>
    <th>Model</th>
    <th>Year</th>
    <th>Color</th>
    <th>Mileage</th>
  </tr>
  <% @cars.each do |car| %>
    <tr>
      <td><%= link_to car.manufacturer.name, manufacturer_path(car.manufacturer) %></td>
      <td><%= link_to car.model, car_path(car) %></td>
      <td><%= car.year %></td>
      <td><%= car.color %></td>
      <td><%= car.mileage %></td>
    </tr>
  <% end %>
</table>

<br>

<%= link_to "List of manufacturers", manufacturers_path %>

car-listings/app/views/cars/new.html.erb
<h2>Enter details for the new car below:</h2>

<%= form_for @car do |f| %>

  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@car.errors.count, "error") %> prohibited
        this car from being saved:
      </h2>
      <ul>
        <% @car.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :manufacturer %><br>
    <%= f.select(:manufacturer_id) do %>
      <% @manufacturers.each do |manufacturer| %>
        <%= content_tag(:option, manufacturer.name, value: manufacturer.id) %>
      <% end %>
    <% end %>
  </p>

  <p>
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </p>

  <p>
    <%= f.label :year %><br>
    <%= f.select :year, (1920)..(2025) %>
  </p>

  <p>
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </p>

  <p>
    <%= f.label :mileage %><br>
    <%= f.text_field :mileage %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

car-listings/app/views/manufacturers/index.html.erb
<h1>Manufacturers</h1>

<%= link_to "Add a new manufacturer", new_manufacturer_path %>

<ul>
  <% @manufacturers.each do |manufacturer| %>
    <li><%= link_to manufacturer.name, manufacturer_path(manufacturer) %></li>
  <% end %>
</ul>

<br>

<%= link_to "List of cars", cars_path %>

car-listings/app/views/manufacturers/new.html.erb
<h2>Enter details for the new manufacturer below:</h2>

<%= form_for @manufacturer do |f| %>

  <% if @manufacturer.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@manufacturer.errors.count, "error") %> prohibited
        this manufacturer from being saved:
      </h2>
      <ul>
        <% @manufacturer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

car-listings/app/views/manufacturers/show.html.erb
<h1><%= @manufacturer.name %></h1>

<h5>Country of origin: <%= @manufacturer.country %></h5>